Add basic i18n support
lukeed/fromnow pull request #10
Opened 2018-09-24 11:54 UTC by NKjoep

2018-09-24 17:13 UTC, lukeed requested changes
Hey, thanks!

Few things:

1) ~~Can you please revert the filename change for tests?~~ _My bad_

2) Let's drop the `periods` object and make it flat/single-level object.

3) No need for `now` key; it's not being used anywhere.

4) Let's take all this `i18n` logic and move it into a new entry file: `src/i18n.js`. I will then follow up this PR with `builder.js` changes to expose it correctly. The idea here is that most people may not care/want the i18n support, but those who do can do `import fromNow from 'fromnow/i18n`.

Thanks!

2018-09-24 17:13 UTC, lukeed commented on README.md
> +  fromnow: 'da ora',
Let's rename this key `future`.

2018-09-24 17:14 UTC, lukeed commented on README.md
> +  ago: 'fa',
And rename this one `past`

2018-09-24 17:14 UTC, lukeed commented on README.md
> +  justnow: 'proprio ora',
Finally, `justnow` can become `now`

2018-09-24 17:16 UTC, lukeed commented on src/index.js
> +	var translations = Object.assign({}, I18N, opts['i18n']);
No need for `Object.assign` here

```js
var translations = opts.i18n || I18N;
// as per review request, "periods" is gone anyway
```

2018-09-25 07:47 UTC, NKjoep commented
Hey Luke, thanks for reviewing it! I did _2)_ and _3)_ (renamed the keys, flattened etc).

I am not sure I understand how you would like to proceed with _4)_ and i18n abstraction. 🙄
The only logic added is the `var translations = opts.i18n || I18n`.

What I would do is to, as you said, move away the `i18n` constant (or constants) so that it can be skipped in the final build.

Please give me some more instruction so I can complete this, or feel free to close PR and proceed independently. No offence taken :D

2020-03-19 14:16 UTC, closed without merging